site_name: "MIDAS Python"
site_author: "Sumit Shekhar"
site_url: https://midas-rnd.github.io/midasapi-python/

extra_css:
  - stylesheets/extra.css

theme:
  # name: shadcn
  name : material
  favicon: assets/favicon.ico
  logo: assets/midas-logo_White.png
  custom_dir: overrides

  palette: 
    scheme: default
    primary: black
    accent: blue

  font:
    text: Roboto Flex
    code: Fragment Mono
  features:
    - navigation.indexes
    - navigation.instant
    - toc.follow
    - navigation.top
    - search.suggest
    - navigation.path
    - content.code.copy
    - header.autohide
    - toc.follow
    - search.suggest
    - header.autohide
    - announce.dismiss
        

plugins:
  - search # put it first to inject out custom code
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: auto
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

markdown_extensions:
 - admonition
 - toc:
      toc_depth: 3
 - tables
 - pymdownx.highlight
 - pymdownx.inlinehilite
 - pymdownx.superfences
 - pymdownx.snippets
 - pymdownx.details
 - md_in_html
 - attr_list
 - pymdownx.blocks.caption
     

extra_javascript:
  - https://cdn.jsdelivr.net/npm/echarts@5.5.1/dist/echarts.min.js
  - assets/tree.js

copyright: "Created by Midas India :  MIDAS CIVIL NX - Python interface"


nav:

  - Introduction: index.md
  - Model: model.md
  - Node: node.md

  - Element:
    - Element: Element/index.md
    - ‎ ‎ ‎ 1D Elements: Element/1D.md
    - ‎ ‎ ‎ 2D Elements: Element/2D.md
    - ‎ ‎ ‎ 3D Elements: Element/3D.md 
    - ‎ ‎ ‎ Stiffness Scale Factor: Element/ElemetScaleFactor.md

  - Section Properties:
    - Section : Section/index.md
    - ‎ ‎ ‎ Standard Section : Section/01_user.md
    - ‎ ‎ ‎ PSC Section: Section/02_psc.md
    - ‎ ‎ ‎ Composite Section : Section/03_composite.md
    - ‎ ‎ ‎ Tapered Section : Section/04_tapered.md
    - ‎ ‎ ‎ Tapered Group : Section/05_taperedgroup.md
    - ‎ ‎ ‎ Value Section : Section/06_value.md
    - ‎ ‎ ‎ Shape : Section/07_shape.md
    - Thickness : Section/09_thickness.md

  - Material Properties:
    - Material : Material/index.md

    - ‎ ‎ ‎ Concrete : Material/001concrete.md
    - ‎ ‎ ‎ Steel : Material/002steel.md
    - ‎ ‎ ‎ User-defined : Material/003usermat.md

    - Creep Shrinkage : Material/010creep.md
    - Compressive Strength : Material/011comp.md
    - Time Dependent Link : Material/012tdlink.md  
    - Change Property :  Material/013changeProp.md

  - Groups:
    - Groups  : Group/index.md
    - ‎ ‎ ‎ Structure Group : Group/001sg.md
    - ‎ ‎ ‎ Boundary Group : Group/002bg.md
    - ‎ ‎ ‎ Load Group: Group/003lg.md
    - ‎ ‎ ‎ Tendon Group: Group/004tg.md


  - Boundary:
    - Boundary : Boundary/index.md
    - ‎ ‎ ‎ Supports : Boundary/01supports.md
    - ‎ ‎ ‎ Elastic Link: Boundary/02elink.md
    - ‎ ‎ ‎ Rigid Link : Boundary/03rlink.md
    - ‎ ‎ ‎ Point Spring : Boundary/04PointSpring.md
    - ‎ ‎ ‎ Multi Linear Function : Boundary/05MLFC.md
    - ‎ ‎ ‎ Beam End Release : Boundary/06beamendrelease.md

  - Load:
    - Load : Load/index.md
    - Load Case : Load/case.md
    - ‎ ‎ ‎ Self Weight : Load/000sw.md
    - ‎ ‎ ‎ Nodal Load : Load/001nodal.md
    - ‎ ‎ ‎ Beam Load: Load/002beam.md
    - ‎ ‎ ‎ Line Beam Load: Load/002Linebeam.md
    - ‎ ‎ ‎ Load To Mass: Load/003LoadToMass.md
    - ‎ ‎ ‎ Nodal Mass: Load/004NodalMass.md
    - ‎ ‎ ‎ Specified Displacement: Load/005spDisp.md
    - ‎ ‎ ‎ Floor Load: Load/006floorload.md
    - ‎ ‎ ‎ Pressure Load: Load/007Pressureload.md
    - ‎ ‎ ‎ Hydrostatic Pressure Load: Load/008Hydrostaticpressure.md
    
  
  - Tendon :
    - ‎ ‎ ‎ Tendon Property : Tendon/001Property.md
    - ‎ ‎ ‎ Tendon Profile : Tendon/002Profile.md
    - ‎ ‎ ‎ Tendon Prestress : Tendon/003Prestress.md


  - Temperature:
    - Temperature Load: Temperature/index.md
    - ‎ ‎ ‎ System : Temperature/001System.md
    - ‎ ‎ ‎ Element: Temperature/002Element.md
    - ‎ ‎ ‎ Gradient: Temperature/003Gradient.md
    - ‎ ‎ ‎ Nodal: Temperature/004Nodal.md
    - ‎ ‎ ‎ Beam Section: Temperature/005Beamsection.md

  - Dynamic Load:
    # - Index : Dynamic/index.md
    - Response Spectrum:
        - RS Function: Dynamic/ResponseSpectrum/RSfunc.md
        - RS Case: Dynamic/ResponseSpectrum/RScase.md
    - Time History :
        - Time History Case: Dynamic/TimeHistory/1_Timehistorycase.md
        - Dynamic Nodal Loads: Dynamic/TimeHistory/DynamicNodalLoads.md
        - Time Varying Static Loads: Dynamic/TimeHistory/TimeVaryingStaticLoads.md
        - Ground Acceleration: Dynamic/TimeHistory/GroundAcceleration.md
        - Multiple Support Excitation: Dynamic/TimeHistory/MultipleSupportExcitation.md

  - Moving Load:
    - Moving Load : MovingLoad/index.md    
    - ‎ ‎ ‎ Code: MovingLoad/000Code.md    
    - ‎ ‎ ‎ Vehicle: MovingLoad/001Vehicle.md    
    - ‎ ‎ ‎ Line Lane: MovingLoad/002LineLane.md    
    - ‎ ‎ ‎ Case: MovingLoad/003VHCase.md     
  
  - Settlement:
    - Settlement : Settlement/index.md
    - ‎ ‎ ‎ Group: Settlement/01Group.md
    - ‎ ‎ ‎ Case: Settlement/02Case.md

  - Story:
    - Story : Story/index.md
  
    
  - Construction Stage:
    - Define Construction Stage: CS/001stage.md
    - Composite Section for CS: CS/002compsec.md
    - Time Loads for CS: CS/003timeloads.md
    - Creep Coefficient for CS: CS/004creepcoeffcs.md
    - Camber for CS: CS/005cambercs.md
  
  - Analysis Control:
    - Analysis Control : AnalysisControl/index.md
    - ‎ ‎ ‎ Main Control Data: AnalysisControl/01MainControlData.md
    - ‎ ‎ ‎ PDelta: AnalysisControl/02Pdelta.md
    - ‎ ‎ ‎ Buckling: AnalysisControl/03Buckling.md
    - ‎ ‎ ‎ EigenValue: AnalysisControl/04EigenValue.md
    - ‎ ‎ ‎ Settlement: AnalysisControl/05Settlement.md
    - ‎ ‎ ‎ Heat of Hydration: AnalysisControl/06HeatOfHydration.md
    - Boundary Change Assignment : AnalysisControl/BoundaryChangeAssignment.md
    
  - View: View/01_view.md

  - Results :
    - ‎ ‎ ‎ Load Combination : Result/01_loadCombination.md
    - ‎ ‎ ‎ Result Table : Result/02_resultTable.md
    - ‎ ‎ ‎ User Defined Table : Result/03_userResultTable.md
    - ‎ ‎ ‎ Result Image : Result/04_resultImage.md

  - Heat of Hydration :  
    - ‎ ‎ ‎ Ambient Temperature Function : HoH/001AmbientTemperatureFunction.md
    - ‎ ‎ ‎ Convection Coefficient Function : HoH/003ConvectionCoefficientFunction.md
    - ‎ ‎ ‎ Convection Boundary : HoH/004ConvectionBoundary.md
    - ‎ ‎ ‎ Prescribed Temperature : HoH/008PrescribedTemperature.md
    - ‎ ‎ ‎ Heat Source Functions : HoH/006HeatSourceFunction.md
    - ‎ ‎ ‎ Assign Heat Source : HoH/002AssignHeatSource.md
    - ‎ ‎ ‎ Pipe Cooling : HoH/007PipeCooling.md
    - ‎ ‎ ‎ Construction Stage Definition: HoH/005CsStage.md
    - ‎ ‎ ‎ HY Result Graph : HoH/009ResultGraph.md

  - Utilities : Utilities/index.md

  - Examples :
    - Examples : Examples/index.md
    - ‎ ‎ ‎ 3-D Simple 2-Bay Frame : Examples/ex01.md
    - ‎ ‎ ‎ Plant Structure : Examples/ex02.md
    - ‎ ‎ ‎ Web Opening : Examples/ex03.md
    - ‎ ‎ ‎ Arch Bridge : Examples/ex04.md
    - ‎ ‎ ‎ PSC Box Girder Bridge : Examples/ex05.md
    - ‎ ‎ ‎ PSC-I Composite Bridge : Examples/ex06.md
    - ‎ ‎ ‎ RC Building : Examples/gen_ex01.md

  # - Graphs : funGRAPH/index.md
  - Release Notes : Release Notes/index.md
  - Discussion : Comments/index.md


